### ISSUE TITLE
Arduino hardware connection to DNF ST300

### ISSUE THREAD

**Issue by jon68z** [tomazf/sony9pin_demo#1]
Can you please explain the Arduino connection to the DNF ST300 controller for this project?  I believe the DNF ST300 uses an RS422 interface, which Arduino did you use and how was it wired up?

Thank you for this.

**Comment by tomazf** [comment]
Hi jon68z,
I used Arduino Mega which has multiple HW serial ports but you can use any board and go with SW serial. It listened simultaneously on two ports - one for controller data and the other one to send parsed data to PC (why wasn't parsing done on PC's side? - because the project was modular and PC SW only controlled vMix). 
The connection to DNF was through MAX422 transceiver chip. And the baud is 38k4.
Tomaz

**Comment by jon68z** [comment]
Thanks for reply.
